version: '2'
services:
  postgresdb:
    image: docker.io/bitnami/postgresql:15
    environment:
      - POSTGRESQL_USERNAME=bn_jasperreports
      - POSTGRESQL_DATABASE=bitnami_jasperreports
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '5432'
    volumes:
      - 'postgresqldb_data:/bitnami/postgresql'
  jasperreports:
    image: docker.io/bitnami/jasperreports:8
    ports:
      - '80:8080'
    volumes:
      - 'jasperreports_data:/bitnami/jasperreports'
    depends_on:
      - postgresdb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - JASPERREPORTS_DATABASE_HOST=postgresdb
      - JASPERREPORTS_DATABASE_PORT_NUMBER=5432
      - JASPERREPORTS_DATABASE_USER=bn_jasperreports
      - JASPERREPORTS_DATABASE_NAME=bitnami_jasperreports
volumes:
  jasperreports_data:
    driver: local
  postgresqldb_data:
    driver: local
